name: .NET

on:
  push:
    branches: [ SpreadSheetTests ]
  pull_request:
    branches: [ SpreadSheetTests ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
     postgres:
      image: postgres:12
      env:
        POSTGRES_USER: scw
        POSTGRES_PASSWORD: scw
        POSTGRES_DB: scw
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: checkout submodule
      run: |
        git submodule update --init --recursive --remote
    - name: Clean
      run: dotnet clean ./SpreadSheetTest/SpreadSheetTest.sln --configuration Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
